---
title: "Schedule"
subtitle: "DATA 202: Statistically Measuring and Modeling Social Justice"
---

::: column-screen-inset-right
| Part | Week | Day | Topics | Labs | Papers | Key readings, exams, other |
|:---------:|:---------:|-----------|-----------|:---------:|:---------:|:---------:|
| I | [1](weeks/week01.html) | Wed, Aug 21 | [Introduction](weeks/week01-slides.html) | [Lab 0](computing.html) |  | Case study 1 files |
|  | [2](weeks/week02.html) | Wed, Aug 28 | [Foundations](weeks/week02-slides.html) |  |  | Pelham (2013, ch. 1) |
|  | [3](weeks/week03.html) | Wed, Sept 4 | [Theory construction](weeks/week03-slides.html) |  |  | [Annotated bibliography](papers/annotated.html) |
|  | [4](weeks/week04.html) | Wed, Sept 11 | [Probability theory](weeks/week04-slides.html) | [Lab 1](labs/lab1.html) |  | Shore (2008); Zuberi (2000) |
| II | [5](weeks/week05.html) | Wed, Sept 18 | [Univariate analysis](weeks/week05-slides.html) |  |  | Wilson et al. (2017) |
|  | [6](weeks/week06.html) | Wed, Sept 25 | [Bivariate analysis](weeks/week06-slides.html) |  | [Paper 1](papers/paper1.html) |  |
|  | [7]() | Wed, Oct 2 | [ ]() |  |  |  |
|  | [8](weeks/week08.html) | Wed, Oct 9 | [Exploratory analysis](weeks/week08-slides.html) |  |  |  |
| III | [9](weeks/week09.html) | Wed, Oct 16 | [Hypothesis testing](weeks/week09-slides.html) |  |  |  |
|  | [10](weeks/week10.html) | Wed, Oct 23 | [Notes on causal theories](weeks/week10-slides.html) | [Lab 2](labs/lab2.html) |  |  |
|  | [11](weeks/week11.html) | Wed, Oct 30 | [Modeling social in/justice](weeks/week11-slides.html) |  |  |  |
|  | [12](weeks/week12.html) | Wed, Nov 6 | [On regression](weeks/week12-slides.html) |  | [Paper 2](papers/paper2.html) |  |
| IV | [13](weeks/week13.html) | Wed, Nov 13 | [More on regression](weeks/week13-slides.html) |  |  |  |
|  | [14](weeks/week14.html) | Wed, Nov 20 | [Statistical learning](weeks/week14-slides.html) | [Lab 3](labs/lab3.html) |  |  |
|  | [15](weeks/week15.html) | Wed, Dec 4 | [Overview of additional models](weeks/week15-slides.html) |  | [Paper 3](papers/paper3.html) |  |
:::

